config/routes.rb
Rails.application.routes.draw do
  resources :tickets

   root 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessor :reqd_time

  class << self
    def inside_members(reqdtime)
      @reqd_time = reqdtime
      (member_status('entry') -member_status('exit')).count
    end

    def member_status(status)
      Ticket.where(
          '(date(timestamp) >= ? AND timestamp <= ? ) and event_type = ?',
          @reqd_time.to_date,
          @reqd_time,
          status.to_s).pluck(:ticket_id).uniq
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index

    begin
      if params[:search]
        @tickets = Ticket.inside_members(params[:search])  if Date.parse(params[:search])
      else
        @tickets = Ticket.count
      end
    rescue
      flash.now[:notice] = "Invalid creation date"
      render :action => 'index'
    end
  end
  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:ticket_id, :event_type, :timestamp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Museum</title>
  <%#= #stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= # javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.number_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Museum Visitors Report</h1>

<%= form_tag tickets_path, :method => 'get' do %>
    <div >
      <%= datetime_field_tag :search,Time.new( 2015, 12, 12, 12, 20, 00 ), min: '2015-12-01T09:00:00+0000', max: '2015-12-30T18:00:00+0000' %>
      <%= submit_tag 'search' %>
    </div>
<% end %>

<table>

  <tbody>
  <br>
  <p>Total Members inside museum is : <b><%=@tickets%></b></p>
  <p>at the time of : <%=  params[:search] %> </p>

  </tbody>
</table>

<br>

<%#= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket.ticket_id %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @ticket.event_type %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @ticket.timestamp %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>